#Just for fun :)
import pyautogui
import time
time.sleep(5)
for i in range(10):
    pyautogui.press("enter")
    pyautogui.press("I")
    pyautogui.press("space")
    pyautogui.press("a")
    pyautogui.press("m")
    pyautogui.press("space")
    pyautogui.press("A")
    pyautogui.press("n")
    pyautogui.press("u")
    pyautogui.press("r")
    pyautogui.press("a")
    pyautogui.press("g")
    pyautogui.press("space")
    pyautogui.press("K")
    pyautogui.press("u")
    pyautogui.press("m")
    pyautogui.press("a")
    pyautogui.press("r")
    pyautogui.press("space")
    pyautogui.press("J")
    pyautogui.press("h")
    pyautogui.press("a")
    pyautogui.press("enter")